import { useState, useEffect } from 'react';
import { X } from 'lucide-react';
import { Room } from '@/src/types';

interface AddGuestModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAdd: (guest: any) => void;
  initialData?: any; // For editing
  rooms: Room[]; // List of all rooms
}

export default function AddGuestModal({ isOpen, onClose, onAdd, initialData, rooms }: AddGuestModalProps) {
  const [name, setName] = useState('');
  const [phone, setPhone] = useState('');
  const [email, setEmail] = useState('');
  const [address, setAddress] = useState('');
  const [checkIn, setCheckIn] = useState('');
  const [checkOut, setCheckOut] = useState('');
  const [room, setRoom] = useState('');

  // Effect to populate form when initialData changes or modal opens
  useEffect(() => {
    if (isOpen && initialData) {
      setName(initialData.name || '');
      setPhone(initialData.phone || '');
      setEmail(initialData.email || '');
      setAddress(initialData.address || '');
      
      const parseToISO = (dateStr: string) => {
         try {
           const d = new Date(dateStr); 
           if (isNaN(d.getTime())) return '';
           const pad = (n: number) => n < 10 ? '0'+n : n;
           return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
         } catch(e) { return ''; }
      };

      setCheckIn(parseToISO(initialData.checkInISO || initialData.checkIn) || '');
      setCheckOut(parseToISO(initialData.checkOutISO || initialData.checkOut) || '');
      setRoom(initialData.room || ''); // Ideally this matches the room_number in value
    } else if (isOpen) {
      if (!initialData) {
        setName('');
        setPhone('');
        setEmail('');
        setAddress('');
        setCheckIn('');
        setCheckOut('');
        setRoom('');
      }
    }
  }, [isOpen, initialData]);

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name || !checkIn || !checkOut || !room) {
      alert("Please fill in required fields (Name, Check-In, Check-Out, Room)");
      return;
    }

    const newGuest = {
      // id generated by backend
      name,
      email,
      phone,
      address,
      avatar: "/avatars/default.jpg", 
      checkIn,
      checkOut,
      room,
      room2: room 
    };

    onAdd(newGuest);
    // Reset form
    setName('');
    setEmail('');
    setPhone('');
    setAddress('');
    setCheckIn('');
    setCheckOut('');
    setRoom('');
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-md mx-4 overflow-hidden max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between p-4 border-b">
          <h3 className="text-lg font-semibold text-gray-800">{initialData ? 'Edit Guest' : 'Add New Guest'}</h3>
          <button onClick={onClose} className="p-1 hover:bg-gray-100 rounded-full transition-colors">
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>
        
        <form onSubmit={handleSubmit} className="p-4 space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Guest Name *</label>
            <input 
              type="text" 
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full text-black border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500"
              placeholder="Enter guest name"
              required
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
             <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
                <input 
                  type="email" 
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-full text-black border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500"
                  placeholder="john@example.com"
                />
             </div>
             <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Phone</label>
                <input 
                  type="tel" 
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  className="w-full text-black border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500"
                  placeholder="555-0123"
                />
             </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Address</label>
            <input 
              type="text" 
              value={address}
              onChange={(e) => setAddress(e.target.value)}
              className="w-full text-black border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500"
              placeholder="123 Main St"
            />
          </div>
          
          <div className="grid grid-cols-2 gap-4">
             <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Check-In *</label>
                <input 
                  type="datetime-local" 
                  value={checkIn}
                  onChange={(e) => setCheckIn(e.target.value)}
                  className="w-full text-black border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500"
                  required
                />
             </div>
             <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Check-Out *</label>
                <input 
                  type="datetime-local" 
                  value={checkOut}
                  onChange={(e) => setCheckOut(e.target.value)}
                  className="w-full text-black border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500"
                  required
                />
             </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Room Number *</label>
            <select
              value={room}
              onChange={(e) => setRoom(e.target.value)}
              className="w-full text-black border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500 bg-white"
              required
            >
               <option value="">Select a room</option>
               {rooms.filter(r => r.status === 'Available' || (initialData && initialData.room === r.room_number)).map((r) => (
                   <option key={r.room_id} value={r.room_number}>
                     {r.room_number} ({r.status})
                   </option>
               ))}
            </select>
          </div>

          <div className="pt-2 flex justify-end gap-3">
             <button 
                type="button" 
                onClick={onClose}
                className="px-4 py-2 border border-gray-300 text-gray-700 rounded text-sm font-medium hover:bg-gray-50"
             >
                Cancel
             </button>
             <button 
                type="submit"
                className="px-4 py-2 bg-blue-800 text-white rounded text-sm font-medium hover:bg-blue-900"
             >
                {initialData ? 'Update Guest' : 'Add Guest'}
             </button>
          </div>
        </form>
      </div>
    </div>
  );
}
